# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f035e0b58516d7401b0530beb645ad483d93010f87b0b61f65ccfb23e68c73eb25bfd5f0efd24d84d4bb503162d1a2a27d64e5793ffcc50dba277381787c0ad3

test:
  secret_key_base: f9163376cce860fe616b17ea9af470a16bd0b0b4edf61b993f045d0480d21f4fd36ac11afaf98880f8c7f1c48377d838190cac84648882a7e84d2af7ecc3d965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
